### ISSUE TITLE
The tutorial does not work and this code seems broken.

### ISSUE THREAD

**Issue by jonny2779** [saucelabs/grunt-init-sauce#3]
It can't find the tasks.

Followed this tutorial: https://docs.saucelabs.com/tutorials/node-js/

![screen shot 2015-02-06 at 10 36 46 am](https://cloud.githubusercontent.com/assets/3011407/6080976/300a91fe-adec-11e4-87e4-460e04379098.png)
![screen shot 2015-02-06 at 10 36 36 am](https://cloud.githubusercontent.com/assets/3011407/6080977/300acbe2-adec-11e4-8ed0-9785a3f70169.png)
![screen shot 2015-02-06 at 10 37 00 am](https://cloud.githubusercontent.com/assets/3011407/6080979/31f6f7aa-adec-11e4-87df-d8b575122fe7.png)

**Comment by McKean** [comment]
I'm experiencing the same issue.

**Comment by McKean** [comment]
A solution is discussed here:
https://github.com/saucelabs/docs/issues/107

> lodash 3 introduces breaking changes. package.json update to "lodash": "~2.4.1" fixed

**Comment by Jonahss** [comment]
fixed in #5
